return {
	-- "saghen/blink.cmp",
	-- version = "1.*",
	-- ---@module 'blink.cmp'
	-- ---@type blink.cmp.Config
	-- dependencies = {
	-- 	"saghen/blink.compat",
	-- },
	-- opts = {
	-- 	keymap = { preset = "default" },
	--
	-- 	appearance = {
	-- 		nerd_font_variant = "mono",
	-- 	},
	--
	-- 	completion = { documentation = { auto_show = true } },
	-- 	fuzzy = { implementation = "rust" },
	-- 	sources = {
	-- 		default = { "lsp", "path", "buffer" },
	-- 	},
	-- 	cmdline = {
	-- 		completion = {
	-- 			menu = {
	-- 				auto_show = true,
	-- 			},
	-- 		},
	-- 	},
	-- },
	-- opts_extend = { "sources.default" },
}
